os: osx
osx_image: xcode11
language: swift
script: xcodebuild clean build -project TravisCIDemo.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iphone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
